version: "3" 
services: 
    web: 

        image: sebp/lighttpd
        deploy: 
            replicas: 3
            resources: 
                limits: 
                    cpus: "0.1" 
                    memory: 50M 
            restart_policy: 
                condition: on-failure 
        ports: 
            - 8008:80
        networks: 
            - webnet 
networks: 
    webnet:
